language: node_js

node_js:
  - node

before_script:
  - npm i -g lintspaces-cli gts typescript
  - npm install --only=production addons-linter

script:
  - gts check
  - lintspaces -nt -d 'spaces' -i 'js-comments' src/options/* src/css/*.css src/typescript/* src/manifest.json
  - npm run build
  - addons-linter firefox
