# Node js managed firefox ext. project
language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

before_script:
  - printf '\033[34mPreparing build tools\033[0m\n'
  - npm i lintspaces-cli eslint addons-linter

script:
  - printf '\033[34mLinting spaces\033[0m\n'
  - ./node_modules/.bin/lintspaces -nt -d 'spaces' -i 'js-comments' src/options/* src/css/*.css src/scripts/*.js src/libs/*.js src/manifest.json
  - printf '\033[34mChecking ECAMScript sources\033[0m\n'
  - export PATH=$PATH:`pwd`/node_modules/.bin/; npm run check
  - printf '\033[34mBuilding addons\033[0m\n'
  - npm run build
  - printf '\033[34mRunning extension lint\033[0m\n'
  - ./node_modules/.bin/addons-linter firefox
  - printf '\033[34mTesting packaging function\033[0m\n'
  - npm run package
  - printf '\033[34mClean Up\033[0m\n'
  - npm run clean
