# Node js managed firefox ext. project
language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules

before_script:
  - npm i lintspaces-cli eslint addons-linter

script:
  - ./node_modules/.bin/lintspaces -nt -d 'spaces' -i 'js-comments' src/options/* src/css/*.css src/scripts/*.js src/libs/*.js src/manifest.json
  - export PATH=$PATH:`pwd`/node_modules/.bin/; npm run check
  - ./node_modules/.bin/addons-linter firefox
  - npm run build
  - npm run package
  - npm run clean
