language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

before_script:
  - npm i -g lintspaces-cli gts typescript
  - npm i --only=production addons-linter

script:
  - gts check
  - lintspaces -nt -d 'spaces' -i 'js-comments' src/options/* src/css/*.css src/typescript/* src/manifest.json
  - npm run build
  - addons-linter firefox
