# Node js managed firefox ext. project
language: node_js

node_js:
  - "8"

stages:
  - prepare-ls
  - prepare-eslint
  - prepare-addonslint
  - check-spaces
  - check-ecmascript
  - check-addons
  - deploy
  - clean

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: prepare-ls
      script: npm i lintspaces-cli
    - stage: prepare-eslint
      script: npm i eslint
    - stage: prepare-addonslint
      script: npm i --only=production addons-linter
    - stage: check-spaces
      script: ./node_modules/.bin/lintspaces -nt -d 'spaces' -i 'js-comments' src/options/* src/css/*.css src/scripts/*.js src/libs/*.js src/manifest.json
    - stage: check-ecmascript
      script: npm run check PATH=$PATH:./node_modules/.bin/
    - stage: check-addons
      script: ./node_modules/.bin/addons-linter firefox
    - stage: deploy
      script:
        - npm run build
        - npm run package
    - stage: clean
      script: npm run clean

